# Generated by Django 6.0.1 on 2026-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf_cnpj', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.CharField(max_length=255)),
                ('tipo_doc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nfe',
            fields=[
                ('chave_nf', models.CharField(max_length=44, primary_key=True, serialize=False)),
                ('data', models.DateField(null=True)),
                ('numero_nf', models.CharField(max_length=20)),
                ('emitente', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=255)),
                ('cnpj_emit', models.CharField(max_length=14)),
                ('cnpj_dest', models.CharField(max_length=14, null=True)),
                ('uf_dest', models.CharField(max_length=2, null=True)),
                ('valor_nf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('transportadora', models.CharField(max_length=255, null=True)),
                ('cidade_origem', models.CharField(max_length=100)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('mod_frete', models.CharField(max_length=10, null=True)),
                ('cfop_predominante', models.CharField(max_length=10, null=True)),
                ('tipo_operacao', models.CharField(max_length=50, null=True)),
                ('qtd_itens', models.IntegerField(default=0)),
                ('cep_origem', models.CharField(max_length=10, null=True)),
                ('cep_destino', models.CharField(max_length=10, null=True)),
                ('distancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arquivo', models.CharField(max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, unique=True, verbose_name='Nome no XML')),
                ('peso_unitario_kg', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Peso Unitário (KG)')),
                ('manual', models.BooleanField(default=False, verbose_name='Editado Manualmente?')),
            ],
            options={
                'verbose_name': 'Mapeamento de Produto',
                'verbose_name_plural': 'Mapeamento de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Cte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_cte_propria', models.CharField(max_length=44)),
                ('chave_nf', models.CharField(max_length=44)),
                ('data', models.DateField(null=True)),
                ('numero_cte', models.CharField(max_length=20)),
                ('emitente', models.CharField(max_length=255)),
                ('cnpj_emit', models.CharField(max_length=14)),
                ('remetente', models.CharField(max_length=255, null=True)),
                ('destinatario', models.CharField(max_length=255, null=True)),
                ('frete_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('numero_nf_cte', models.CharField(max_length=20, null=True)),
                ('cidade_origem', models.CharField(max_length=100)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('pedagio_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('chave_ref_cte', models.CharField(blank=True, max_length=44, null=True)),
                ('tp_cte', models.CharField(default='0', max_length=10)),
                ('arquivo', models.CharField(max_length=255)),
                ('etapa_manual', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('chave_cte_propria', 'chave_nf')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nf', models.CharField(max_length=44)),
                ('numero_nf', models.CharField(max_length=20)),
                ('emitente', models.CharField(max_length=255)),
                ('item_num', models.CharField(max_length=10)),
                ('produto', models.CharField(max_length=255)),
                ('ncm', models.CharField(max_length=20, null=True)),
                ('cfop', models.CharField(max_length=10, null=True)),
                ('unidade', models.CharField(max_length=10, null=True)),
                ('qtd_display', models.CharField(max_length=20, verbose_name='Peso Estimado Unitário')),
                ('qtd_formatada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantidade Itens')),
                ('qtd_float', models.DecimalField(decimal_places=4, max_digits=15)),
                ('vl_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('arquivo', models.CharField(max_length=255)),
                ('peso_estimado_total', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
            ],
            options={
                'unique_together': {('chave_nf', 'item_num')},
            },
        ),
        migrations.CreateModel(
            name='MemoriaIa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfop', models.CharField(max_length=10)),
                ('fluxo', models.CharField(max_length=50)),
                ('tipo_definido', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('cfop', 'fluxo')},
            },
        ),
    ]
