# Generated by Django 6.0.1 on 2026-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('cnpj', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CNPJ/CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('perfil_tributario', models.CharField(choices=[('Simples', 'Simples Nacional'), ('Padrao', 'Padrão (Lucro Real/Presumido)')], default='Padrao', max_length=20, verbose_name='Perfil Tributário')),
                ('cidades_atendidas', models.TextField(blank=True, help_text='Separe as cidades por vírgula', null=True)),
                ('tipos_frete', models.CharField(blank=True, help_text='Ex: CIF, FOB, RETIRA, SEM FRETE', max_length=255, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
            },
        ),
    ]
